package com.techhispania.imperator.core.handlers;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.sun.net.httpserver.HttpExchange;
import com.techhispania.imperator.common.utils.Constants;

/**
 * The code of this class was generated by ChatGPT<br>
 * Basically this is what is doing:<br>
 * 1. Reads the HTTP request as bytes<br>
 * 2. Detects boundaries exactly and includes the leading --<br>
 * 3. Removes extra trailing CRLF automatically because of boundary detection<br>
 * 4. Saves file in destination directory<br>
 */
public class HandleUploadImpl implements HandleUpload {

	private static final Logger logger = LogManager.getLogger(HandleUploadImpl.class);
	
	private static final String DESTINATION_FOLDER = "../deployed";
	
	public Optional<String> handleUpload(HttpExchange exchange, byte[] bodyBytes) throws IOException {

		Optional<String> rawBoundary = retrieveBoundary(exchange);
		
		if (rawBoundary.isEmpty()) {
			logger.error("Error. No boundary found in Content-Type");
			return Optional.empty();
		}
		
		byte[] boundaryBytes = rawBoundary.get().getBytes(StandardCharsets.ISO_8859_1);
		logger.debug("Boundary: {}", new String(boundaryBytes));

		int pos = 0;
		while (pos < bodyBytes.length) {
			// Find next boundary
			int boundaryStart = indexOf(bodyBytes, boundaryBytes, pos);
			if (boundaryStart < 0)
				break;
			int partStart = boundaryStart + boundaryBytes.length + 2; // skip \r\n
			int nextBoundary = indexOf(bodyBytes, boundaryBytes, partStart);
			if (nextBoundary < 0)
				break;

			int partLength = nextBoundary - partStart;
			byte[] partBytes = Arrays.copyOfRange(bodyBytes, partStart, partStart + partLength);

			// Split headers and content (binary-safe)
			int headerEnd = indexOf(partBytes, "\r\n\r\n".getBytes(StandardCharsets.ISO_8859_1), 0);
			if (headerEnd > 0) {
				byte[] headersBytes = Arrays.copyOfRange(partBytes, 0, headerEnd);

				int contentEnd = partBytes.length;
				if (contentEnd >= 2 && partBytes[contentEnd - 2] == '\r' && partBytes[contentEnd - 1] == '\n') {
					contentEnd -= 2; // remove trailing CRLF
				}

				byte[] fileBytes = Arrays.copyOfRange(partBytes, headerEnd + 4, contentEnd);

				String headers = new String(headersBytes, StandardCharsets.ISO_8859_1);
				if (headers.contains("filename=")) {
					String filename = headers.split("filename=\"")[1].split("\"")[0];
					File uploadsDir = new File(DESTINATION_FOLDER);
					if (!uploadsDir.exists())
						uploadsDir.mkdirs();
					File outFile = new File(uploadsDir, filename);
					try (FileOutputStream fos = new FileOutputStream(outFile)) {
						fos.write(fileBytes);
					}
					return Optional.of(filename);
				}
			}
			pos = nextBoundary;
		}
		return Optional.empty();
	}

	@Override
	public Map<String, String> parseMultipartFormFields(String body, String boundary) {
	    Map<String, String> fields = new HashMap<>();

	    // split by boundary
	    String[] parts = body.split(Pattern.quote(boundary));

	    for (String part : parts) {
	        part = part.trim();
	        if (part.isEmpty()) continue;

	        // find header/content separator
	        int sep = part.indexOf("\r\n\r\n");
	        if (sep < 0) continue;

	        String headers = part.substring(0, sep).trim();
	        String content = part.substring(sep + 4).trim(); // remove CRLF

	        // extract name="..."
	        Matcher m = Pattern.compile("name=\"([^\"]+)\"").matcher(headers);
	        if (!m.find()) continue;

	        String fieldName = m.group(1);

	        // ignore file uploads (they contain filename="...")
	        if (headers.contains("filename=")) continue;

	        fields.put(fieldName, content);
	    }
	    return fields;
	}
	
	@Override
	public Optional<String> retrieveBoundary(HttpExchange exchange) {
		String contentType = exchange.getRequestHeaders().getFirst(Constants.HEADER_CONTENT_TYPE);

		if (contentType == null || contentType.length() == 0)
			return Optional.empty();
		
		String rawBoundary = contentType.split("boundary=")[1];
		
		if (rawBoundary == null || rawBoundary.length() == 0)
			return Optional.empty();
		
		byte[] boundaryBytes = ("--" + rawBoundary).getBytes(StandardCharsets.ISO_8859_1);
		String boundary = new String(boundaryBytes);
		
		logger.debug("Boundary: {}", boundary);
		return Optional.of(boundary);
	}
	
	// Helper method to find byte array in another byte array
	private int indexOf(byte[] array, byte[] target, int fromIndex) {
		outer: for (int i = fromIndex; i <= array.length - target.length; i++) {
			for (int j = 0; j < target.length; j++) {
				if (array[i + j] != target[j])
					continue outer;
			}
			return i;
		}
		return -1;
	}
}
